"""Shared SQLAlchemy model primitives."""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import DateTime, MetaData, Numeric, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

MONEY_PRECISION = 16
MONEY_SCALE = 2
ZERO_MONEY = Decimal("0.00")


class Base(DeclarativeBase):
    """Declarative base using deterministic migration constraint names."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """UUID primary key generated by the application."""

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)


class TimestampMixin:
    """Timezone-aware creation and modification timestamps."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


def money_column(
    *, nullable: bool = False, default: Decimal | None = ZERO_MONEY
) -> Mapped[Decimal]:
    """Build a NUMERIC-backed mapped column for financial values."""

    if default is None:
        return mapped_column(Numeric(MONEY_PRECISION, MONEY_SCALE), nullable=nullable)
    return mapped_column(
        Numeric(MONEY_PRECISION, MONEY_SCALE),
        nullable=nullable,
        default=default,
        server_default=str(default),
    )
