"""initial pesticide shop schema

Revision ID: 8b221b346f3b
Revises:
Create Date: 2026-08-22 13:35:14.233922
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "8b221b346f3b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Every PostgreSQL enum type this migration creates, named so the downgrade can
#: remove them; SQLAlchemy creates them implicitly with the tables that use them.
ENUM_TYPES = (
    "email_status",
    "inventory_transaction_type",
    "payment_direction",
    "payment_method",
    "payment_status",
    "purchase_status",
    "sale_status",
    "setting_category",
    "user_role",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column(
            "category",
            sa.Enum(
                "GENERAL",
                "SHOP",
                "EMAIL",
                "PRINTER",
                "RECEIPT",
                "BACKUP",
                "DATABASE",
                "SECURITY",
                name="setting_category",
            ),
            nullable=False,
        ),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("is_secret", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_settings")),
        sa.UniqueConstraint("category", "key", name="uq_setting_category_key"),
    )
    op.create_table(
        "customers",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("cnic", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("cnic", name=op.f("uq_customers_cnic")),
    )
    op.create_index("ix_customers_name", "customers", ["name"], unique=False)
    op.create_index("ix_customers_phone", "customers", ["phone"], unique=False)
    op.create_table(
        "dealers",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("business_name", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("cnic", sa.String(length=32), nullable=True),
        sa.Column("tax_number", sa.String(length=80), nullable=True),
        sa.Column("territory", sa.String(length=120), nullable=True),
        sa.Column(
            "credit_limit", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column(
            "balance", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("credit_limit >= 0", name=op.f("ck_dealers_credit_limit_nonnegative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dealers")),
        sa.UniqueConstraint("cnic", name=op.f("uq_dealers_cnic")),
        sa.UniqueConstraint("tax_number", name=op.f("uq_dealers_tax_number")),
    )
    op.create_index("ix_dealers_name", "dealers", ["name"], unique=False)
    op.create_index("ix_dealers_phone", "dealers", ["phone"], unique=False)
    op.create_index("ix_dealers_territory", "dealers", ["territory"], unique=False)
    op.create_table(
        "document_sequences",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("prefix", sa.String(length=20), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("current_value", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_document_sequences")),
    )
    op.create_table(
        "email_history",
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("template", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENDING", "SENT", "FAILED", name="email_status"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("attachment_name", sa.String(length=255), nullable=True),
        sa.Column("attachment_data", sa.LargeBinary(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_history")),
    )
    op.create_index(
        "ix_email_history_entity", "email_history", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(op.f("ix_email_history_status"), "email_history", ["status"], unique=False)
    op.create_index(
        "ix_email_history_status_created", "email_history", ["status", "created_at"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("manufacturer", sa.String(length=140), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("active_ingredient", sa.String(length=180), server_default="", nullable=False),
        sa.Column("formulation", sa.String(length=100), server_default="", nullable=False),
        sa.Column("pack_size", sa.String(length=80), server_default="", nullable=False),
        sa.Column("registration_number", sa.String(length=100), server_default="", nullable=False),
        sa.Column("unit", sa.String(length=30), server_default="PACK", nullable=False),
        sa.Column("category", sa.String(length=80), server_default="PESTICIDE", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "default_purchase_price",
            sa.Numeric(precision=16, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "default_sale_price",
            sa.Numeric(precision=16, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column("minimum_stock", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_purchase_price >= 0", name=op.f("ck_products_purchase_price_nonnegative")
        ),
        sa.CheckConstraint(
            "default_sale_price >= 0", name=op.f("ck_products_sale_price_nonnegative")
        ),
        sa.CheckConstraint(
            "minimum_stock >= 0", name=op.f("ck_products_minimum_stock_nonnegative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint(
            "manufacturer", "name", "formulation", "pack_size", name="uq_product_variant"
        ),
    )
    op.create_index(
        "ix_products_manufacturer_name", "products", ["manufacturer", "name"], unique=False
    )
    op.create_table(
        "suppliers",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("tax_number", sa.String(length=80), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "balance", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("tax_number", name=op.f("uq_suppliers_tax_number")),
    )
    op.create_index("ix_suppliers_name", "suppliers", ["name"], unique=False)
    op.create_index("ix_suppliers_phone", "suppliers", ["phone"], unique=False)
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "MANAGER", "SALESPERSON", "INVENTORY_MANAGER", name="user_role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("must_change_password", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "ix_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_index(
        "ix_users_username_lower", "users", [sa.literal_column("lower(username)")], unique=True
    )
    op.create_table(
        "audit_logs",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_or_machine", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_action_created", "audit_logs", ["action", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_user_created", "audit_logs", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "purchases",
        sa.Column("purchase_number", sa.String(length=40), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("purchase_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "subtotal", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column(
            "discount", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column("tax", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False),
        sa.Column(
            "total", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column(
            "paid_amount", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column(
            "remaining_amount",
            sa.Numeric(precision=16, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sa.Enum("PAID", "PARTIALLY_PAID", "UNPAID", "REFUNDED", name="payment_status"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "COMPLETED", "CANCELLED", name="purchase_status"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("discount >= 0", name=op.f("ck_purchases_discount_nonnegative")),
        sa.CheckConstraint(
            "paid_amount >= 0 AND paid_amount <= total", name=op.f("ck_purchases_paid_within_total")
        ),
        sa.CheckConstraint(
            "remaining_amount = total - paid_amount",
            name=op.f("ck_purchases_remaining_matches_total"),
        ),
        sa.CheckConstraint("subtotal >= 0", name=op.f("ck_purchases_subtotal_nonnegative")),
        sa.CheckConstraint("tax >= 0", name=op.f("ck_purchases_tax_nonnegative")),
        sa.CheckConstraint("total >= 0", name=op.f("ck_purchases_total_nonnegative")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_purchases_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_purchases_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchases")),
        sa.UniqueConstraint("purchase_number", name=op.f("uq_purchases_purchase_number")),
    )
    op.create_index(
        "ix_purchases_supplier_date", "purchases", ["supplier_id", "purchase_date"], unique=False
    )
    op.create_table(
        "sales",
        sa.Column("invoice_number", sa.String(length=40), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("dealer_id", sa.UUID(), nullable=True),
        sa.Column("recipient_type", sa.String(length=20), nullable=False),
        sa.Column("order_number", sa.String(length=60), nullable=True),
        sa.Column("territory", sa.String(length=120), nullable=True),
        sa.Column("delivery_address", sa.Text(), nullable=True),
        sa.Column("policy", sa.String(length=120), nullable=True),
        sa.Column("store", sa.String(length=120), nullable=True),
        sa.Column("sale_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "subtotal", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column(
            "discount", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column("tax", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False),
        sa.Column(
            "total", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column(
            "paid_amount", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column(
            "remaining_amount",
            sa.Numeric(precision=16, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sa.Enum("PAID", "PARTIALLY_PAID", "UNPAID", "REFUNDED", name="payment_status"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("status", sa.Enum("COMPLETED", "VOIDED", name="sale_status"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (customer_id IS NOT NULL AND dealer_id IS NOT NULL)",
            name=op.f("ck_sales_ck_sales_one_recipient"),
        ),
        sa.CheckConstraint(
            "discount >= 0 AND discount <= subtotal", name=op.f("ck_sales_ck_sales_discount")
        ),
        sa.CheckConstraint(
            "paid_amount >= 0 AND paid_amount <= total", name=op.f("ck_sales_ck_sales_paid")
        ),
        sa.CheckConstraint(
            "remaining_amount = total - paid_amount", name=op.f("ck_sales_ck_sales_remaining")
        ),
        sa.CheckConstraint("subtotal >= 0", name=op.f("ck_sales_ck_sales_subtotal")),
        sa.CheckConstraint("tax >= 0", name=op.f("ck_sales_ck_sales_tax")),
        sa.CheckConstraint(
            "total = subtotal - discount + tax", name=op.f("ck_sales_ck_sales_total")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_sales_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_sales_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dealer_id"],
            ["dealers.id"],
            name=op.f("fk_sales_dealer_id_dealers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales")),
        sa.UniqueConstraint("invoice_number", name=op.f("uq_sales_invoice_number")),
    )
    op.create_index("ix_sales_created_by_date", "sales", ["created_by", "sale_date"], unique=False)
    op.create_index("ix_sales_customer_date", "sales", ["customer_id", "sale_date"], unique=False)
    op.create_index("ix_sales_date", "sales", ["sale_date"], unique=False)
    op.create_index("ix_sales_dealer_date", "sales", ["dealer_id", "sale_date"], unique=False)
    op.create_table(
        "payments",
        sa.Column("sale_id", sa.UUID(), nullable=True),
        sa.Column("purchase_id", sa.UUID(), nullable=True),
        sa.Column(
            "method",
            sa.Enum(
                "CASH", "CARD", "BANK_TRANSFER", "MOBILE_WALLET", "OTHER", name="payment_method"
            ),
            nullable=False,
        ),
        sa.Column(
            "direction", sa.Enum("INCOMING", "OUTGOING", name="payment_direction"), nullable=False
        ),
        sa.Column(
            "amount", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column("reference", sa.String(length=160), nullable=True),
        sa.Column("received_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_amount_positive")),
        sa.CheckConstraint(
            "num_nonnulls(sale_id, purchase_id) = 1", name=op.f("ck_payments_exactly_one_document")
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchases.id"],
            name=op.f("fk_payments_purchase_id_purchases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["received_by"],
            ["users.id"],
            name=op.f("fk_payments_received_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"], ["sales.id"], name=op.f("fk_payments_sale_id_sales"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index("ix_payments_created", "payments", ["created_at"], unique=False)
    op.create_index("ix_payments_purchase", "payments", ["purchase_id"], unique=False)
    op.create_index("ix_payments_sale", "payments", ["sale_id"], unique=False)
    op.create_table(
        "purchase_items",
        sa.Column("purchase_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "purchase_price",
            sa.Numeric(precision=16, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "line_total", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "line_total = purchase_price * quantity",
            name=op.f("ck_purchase_items_line_total_matches"),
        ),
        sa.CheckConstraint("purchase_price >= 0", name=op.f("ck_purchase_items_price_nonnegative")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_purchase_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_purchase_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchases.id"],
            name=op.f("fk_purchase_items_purchase_id_purchases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_items")),
    )
    op.create_index("ix_purchase_items_purchase", "purchase_items", ["purchase_id"], unique=False)
    op.create_table(
        "stock_batches",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("purchase_id", sa.UUID(), nullable=False),
        sa.Column("purchase_item_id", sa.UUID(), nullable=False),
        sa.Column("batch_number", sa.String(length=100), nullable=False),
        sa.Column("manufacture_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("quantity_received", sa.Integer(), nullable=False),
        sa.Column("quantity_available", sa.Integer(), nullable=False),
        sa.Column("cartons", sa.Integer(), server_default="0", nullable=False),
        sa.Column("packs_per_carton", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "purchase_price",
            sa.Numeric(precision=16, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "selling_price",
            sa.Numeric(precision=16, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column("location", sa.String(length=160), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cartons >= 0", name=op.f("ck_stock_batches_ck_stock_batches_cartons")),
        sa.CheckConstraint(
            "expiry_date IS NULL OR manufacture_date IS NULL OR expiry_date >= manufacture_date",
            name=op.f("ck_stock_batches_ck_stock_batches_dates"),
        ),
        sa.CheckConstraint(
            "packs_per_carton >= 0", name=op.f("ck_stock_batches_ck_stock_batches_packs")
        ),
        sa.CheckConstraint(
            "purchase_price >= 0", name=op.f("ck_stock_batches_ck_stock_batches_purchase_price")
        ),
        sa.CheckConstraint(
            "quantity_available >= 0 AND quantity_available <= quantity_received",
            name=op.f("ck_stock_batches_ck_stock_batches_available_valid"),
        ),
        sa.CheckConstraint(
            "quantity_received > 0",
            name=op.f("ck_stock_batches_ck_stock_batches_received_positive"),
        ),
        sa.CheckConstraint(
            "selling_price >= 0", name=op.f("ck_stock_batches_ck_stock_batches_selling_price")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_stock_batches_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchases.id"],
            name=op.f("fk_stock_batches_purchase_id_purchases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_item_id"],
            ["purchase_items.id"],
            name=op.f("fk_stock_batches_purchase_item_id_purchase_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_stock_batches_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_batches")),
        sa.UniqueConstraint("product_id", "batch_number", name="uq_stock_batches_product_batch"),
    )
    op.create_index(
        "ix_stock_batches_available", "stock_batches", ["quantity_available"], unique=False
    )
    op.create_index(
        "ix_stock_batches_product_expiry",
        "stock_batches",
        ["product_id", "expiry_date"],
        unique=False,
    )
    op.create_index("ix_stock_batches_supplier", "stock_batches", ["supplier_id"], unique=False)
    op.create_table(
        "sale_items",
        sa.Column("sale_id", sa.UUID(), nullable=False),
        sa.Column("stock_batch_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("batch_number", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "unit_price", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column(
            "price", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column(
            "discount", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column(
            "total", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column(
            "purchase_cost",
            sa.Numeric(precision=16, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "other_cost", sa.Numeric(precision=16, scale=2), server_default="0.00", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discount >= 0 AND discount <= price", name=op.f("ck_sale_items_ck_sale_items_discount")
        ),
        sa.CheckConstraint(
            "price = unit_price * quantity", name=op.f("ck_sale_items_ck_sale_items_gross")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sale_items_ck_sale_items_quantity")),
        sa.CheckConstraint(
            "total = price - discount", name=op.f("ck_sale_items_ck_sale_items_total")
        ),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_sale_items_ck_sale_items_unit_price")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_sale_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"], ["sales.id"], name=op.f("fk_sale_items_sale_id_sales"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["stock_batch_id"],
            ["stock_batches.id"],
            name=op.f("fk_sale_items_stock_batch_id_stock_batches"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_items")),
        sa.UniqueConstraint("sale_id", "stock_batch_id", name="uq_sale_items_batch"),
    )
    op.create_index("ix_sale_items_product", "sale_items", ["product_id"], unique=False)
    op.create_index("ix_sale_items_stock_batch", "sale_items", ["stock_batch_id"], unique=False)
    op.create_table(
        "stock_movements",
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "PURCHASE", "SALE", "ADJUSTMENT", "TRANSFER", name="inventory_transaction_type"
            ),
            nullable=False,
        ),
        sa.Column("quantity_change", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column("reference_id", sa.UUID(), nullable=False),
        sa.Column("reference_type", sa.String(length=50), nullable=False),
        sa.Column("performed_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "balance_after >= 0", name=op.f("ck_stock_movements_ck_stock_movements_balance")
        ),
        sa.CheckConstraint(
            "quantity_change <> 0", name=op.f("ck_stock_movements_ck_stock_movements_nonzero")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["stock_batches.id"],
            name=op.f("fk_stock_movements_batch_id_stock_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["performed_by"],
            ["users.id"],
            name=op.f("fk_stock_movements_performed_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movements")),
    )
    op.create_index(
        "ix_stock_movements_batch_created",
        "stock_movements",
        ["batch_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_reference",
        "stock_movements",
        ["reference_type", "reference_id"],
        unique=False,
    )
    op.execute(
        """
        CREATE FUNCTION reject_immutable_row_change() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% rows are immutable', TG_TABLE_NAME;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER audit_logs_immutable
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION reject_immutable_row_change();

        CREATE TRIGGER payments_immutable
        BEFORE UPDATE OR DELETE ON payments
        FOR EACH ROW EXECUTE FUNCTION reject_immutable_row_change();

        CREATE TRIGGER stock_movements_immutable
        BEFORE UPDATE OR DELETE ON stock_movements
        FOR EACH ROW EXECUTE FUNCTION reject_immutable_row_change();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION reject_immutable_row_change() CASCADE")
    op.drop_index("ix_stock_movements_reference", table_name="stock_movements")
    op.drop_index("ix_stock_movements_batch_created", table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index("ix_sale_items_stock_batch", table_name="sale_items")
    op.drop_index("ix_sale_items_product", table_name="sale_items")
    op.drop_table("sale_items")
    op.drop_index("ix_stock_batches_supplier", table_name="stock_batches")
    op.drop_index("ix_stock_batches_product_expiry", table_name="stock_batches")
    op.drop_index("ix_stock_batches_available", table_name="stock_batches")
    op.drop_table("stock_batches")
    op.drop_index("ix_purchase_items_purchase", table_name="purchase_items")
    op.drop_table("purchase_items")
    op.drop_index("ix_payments_sale", table_name="payments")
    op.drop_index("ix_payments_purchase", table_name="payments")
    op.drop_index("ix_payments_created", table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_sales_dealer_date", table_name="sales")
    op.drop_index("ix_sales_date", table_name="sales")
    op.drop_index("ix_sales_customer_date", table_name="sales")
    op.drop_index("ix_sales_created_by_date", table_name="sales")
    op.drop_table("sales")
    op.drop_index("ix_purchases_supplier_date", table_name="purchases")
    op.drop_table("purchases")
    op.drop_index("ix_audit_logs_user_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_users_username_lower", table_name="users")
    op.drop_index("ix_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_suppliers_phone", table_name="suppliers")
    op.drop_index("ix_suppliers_name", table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index("ix_products_manufacturer_name", table_name="products")
    op.drop_table("products")
    op.drop_index("ix_email_history_status_created", table_name="email_history")
    op.drop_index(op.f("ix_email_history_status"), table_name="email_history")
    op.drop_index("ix_email_history_entity", table_name="email_history")
    op.drop_table("email_history")
    op.drop_table("document_sequences")
    op.drop_index("ix_dealers_territory", table_name="dealers")
    op.drop_index("ix_dealers_phone", table_name="dealers")
    op.drop_index("ix_dealers_name", table_name="dealers")
    op.drop_table("dealers")
    op.drop_index("ix_customers_phone", table_name="customers")
    op.drop_index("ix_customers_name", table_name="customers")
    op.drop_table("customers")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
    # Dropping the tables leaves their enum types behind, and the next upgrade then
    # fails on "type ... already exists". The types are created with the first table
    # that uses them, so they are removed here with the last one.
    for name in ENUM_TYPES:
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
